package com.all.backend.commons;

public interface BackendConstants {

	String CONVERT_STATS_TO_FEED_TYPE = "CONVERT _STATS_TO_FEED";
	String SEND_ALERT_EMAIL_REQUEST_TYPE = "SEND_ALERT_EMAIL_REQUEST";
	String SEND_PENDING_EMAIL_REQUEST_TYPE = "SEND_PENDING_EMAIL_REQUEST";
	String SEND_SIGNUP_EMAIL_REQUEST_TYPE = "SEND_SIGNUP_EMAIL_REQUEST";
	String SEND_RESET_PASSWORD_EMAIL_REQUEST_TYPE = "SEND_RESET_PASSWORD_EMAIL_REQUEST";
}
